### ISSUE TITLE
can play?

### ISSUE THREAD

**Issue by sanderpick** [sanderpick/wolfpack-cli#2]
so far, @durwoodthegreat, @robinkraft, and @eightysteele have signed up ... boom. if we use this thing, i bet we'll quickly find out what needs to be added, what works, what sucks, etc.

boom
![Screen Shot 2013-04-15 at 3 35 05 PM](https://f.cloud.github.com/assets/361000/383584/1d12cf18-a61d-11e2-96cd-677894180454.png)

**Comment by andrewxhill** [comment]
boom

![Screen Shot 2013-04-15 at 6 52 02 PM](https://f.cloud.github.com/assets/370259/383623/23c5a7fc-a61f-11e2-9ee8-06d160eff60d.png)

**Comment by sanderpick** [comment]
fuck yeah

**Comment by andrewxhill** [comment]
was on the default mac node v 0.6.x kept getting an error the other day. 0.10.x works though fyi

**Comment by sanderpick** [comment]
word … if you run the wolfpack-server locally, you may run into issues with 0.10.x … like specifically I think the `time` module needs 0.8.x .. will get updated soon im sure

**Comment by andrewxhill** [comment]
k, gtk

**Comment by danhammer** [comment]
having trouble with node.  soon to be on it.

**Comment by eightysteele** [comment]
When you install grr don't use sudo

**Comment by andrewxhill** [comment]
no, first do
sudo rm /*

On Mon, Apr 15, 2013 at 7:06 PM, Aaron Steele notifications@github.comwrote:

> When you install grr don't use sudo
> On Apr 15, 2013 4:02 PM, "Dan" notifications@github.com wrote:
> 
> > having trouble with node. soon to be on it.
> > 
> > On Mon, Apr 15, 2013 at 4:00 PM, Andrew W. Hill <
> > notifications@github.com>wrote:
> > 
> > > k, gtk
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub<
> > 
> > https://github.com/sanderpick/wolfpack-cli/issues/2#issuecomment-16416548>
> > 
> > > .
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/sanderpick/wolfpack-cli/issues/2#issuecomment-16416640>
> > 
> > .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/sanderpick/wolfpack-cli/issues/2#issuecomment-16416789
> .

## 

andrew@vizzuality.com
http://www.vizzuality.com

**Comment by andrewxhill** [comment]
don't do that

On Mon, Apr 15, 2013 at 7:07 PM, Andrew Hill andrewxhill@gmail.com wrote:

> no, first do
> sudo rm /*
> 
> On Mon, Apr 15, 2013 at 7:06 PM, Aaron Steele notifications@github.comwrote:
> 
> > When you install grr don't use sudo
> > On Apr 15, 2013 4:02 PM, "Dan" notifications@github.com wrote:
> > 
> > > having trouble with node. soon to be on it.
> > > 
> > > On Mon, Apr 15, 2013 at 4:00 PM, Andrew W. Hill <
> > > notifications@github.com>wrote:
> > > 
> > > > k, gtk
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub<
> > > 
> > > https://github.com/sanderpick/wolfpack-cli/issues/2#issuecomment-16416548>
> > > 
> > > > .
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub<
> > > https://github.com/sanderpick/wolfpack-cli/issues/2#issuecomment-16416640>
> > > 
> > > .
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/sanderpick/wolfpack-cli/issues/2#issuecomment-16416789
> > .
> 
> ## 
> 
> andrew@vizzuality.com
> http://www.vizzuality.com

## 

andrew@vizzuality.com
http://www.vizzuality.com

**Comment by sanderpick** [comment]
haha

**Comment by danhammer** [comment]
Oh fuck.  I just erased everything.

**Comment by robinkraft** [comment]
Right - it's sudo rm -rf /*

:D

**Comment by andrewxhill** [comment]
Ah yeah yeah, good catch

**Comment by andrewxhill** [comment]
You aren't real men until you have hit enter on that one

**Comment by sanderpick** [comment]
@eightysteele without sudo was it able to add `grr` to your PATH?

**Comment by sanderpick** [comment]
russian roulette with random commands ...

**Comment by andrewxhill** [comment]
i did no sudo grr install and it worked fine

**Comment by sanderpick** [comment]
i must have diff permissions on local .

**Comment by eightysteele** [comment]
Amazing

**Comment by andrewxhill** [comment]
yeah, tbh i fubared some things on my mac over the past few days. see this comment https://github.com/sanderpick/wolfpack-cli/issues/2#issuecomment-16417056

**Comment by andrewxhill** [comment]
so i think like /usr/local/var and stuff are now pretty globally usable. but also I thought npm was primarily non-sudo?

**Comment by sanderpick** [comment]
listing tasks would be cool ..... or just updates for that day if we are not parsing responses into tasks yet...

what i really want is,

`grr massage --happy_ending`

**Comment by sanderpick** [comment]
it is non-sudo but the package.json in grr instructs it to link the executable into /user/local/bin ... which is usually sudo only, i think

**Comment by eightysteele** [comment]
Easter egg #1

**Comment by andrewxhill** [comment]
one of the earliest things we should consider adding is the # parse for github issues. then you could quickly review tickets mentioned in a teams email.

grr team list issues pretty_print

**Comment by andrewxhill** [comment]
i guess we would want to parse full github issues urls, not #numbers

**Comment by robinkraft** [comment]
+1

**Comment by andrewxhill** [comment]
| team member | project | issue |
| --- | --- | --- |
| pick | wolfpack | #1 |
| steele | mol | #1000 |
| kraft | wri | #222 |

to start

**Comment by sanderpick** [comment]
we could have syntax that made it easier to link .... haha, just saw ^^^^ ... +1 dude

**Comment by eightysteele** [comment]
+1

**Comment by sanderpick** [comment]
we should also consider if the current one-way team arch is what we want ... its more like google circles right now ... it makes for more flex but may not have the intended teams functionality that we originally discussed ..

**Comment by andrewxhill** [comment]
I def can see the ease of it just as it is. Not sure.

**Comment by danhammer** [comment]
i'm in, by the way.

![](http://i.imgur.com/u62542U.png)

**Comment by andrewxhill** [comment]
what if it was like it is, but then I worked on `projects` so I could markup my email a bit

single line single word = project name

```
cartodb

today i worked on issue #222, #22 with @someotherperson

wri

closing the ie issues with the slider
```

etc

**Comment by andrewxhill** [comment]
so then, i could subscribe to teams and/or projects

**Comment by eightysteele** [comment]
Dude yes I like that a lot subscribing to a project or team is gold

**Comment by andrewxhill** [comment]
I feel like we are going to want a bit more controlled structure/vocab. One of the biggest wins I think it could have is if, say we were all working on the wri project and adding news bits each day. As a proj manager or whatever, I'd love to run

```
grr project news wri week
```

and it would give me an itemized news list for the week on the project. i wouldn't really want pithy things, just short sweet tidbits, close to what you would dump into a NEWS.md file no?

**Comment by andrewxhill** [comment]
Things I want to know,

what projects were worked on
what issues were discussed
what issues were closed

others?

**Comment by sanderpick** [comment]
yeah dig it (re: https://github.com/sanderpick/wolfpack-cli/issues/2#issuecomment-16417851).... if we ride on the current one-way teams... it would be more like subscribing to a project or person ... in other words, adding a project or a person to a team.

`grr teams add <username || projectname> <teamname>`

right?

**Comment by sanderpick** [comment]
yes man... love that perspective ...

**Comment by sanderpick** [comment]
unless for projects, you could skip the team abstraction and just follow it standalone like ... that's prob better

**Comment by sanderpick** [comment]
marinating for now ... i will write up some basic notes on the overall arch / developing ... and through in a wiki (cli and server)

**Comment by andrewxhill** [comment]
right, i really like the idea of subscribing to people or projects or both and letting the system put it all together for you in a structured, non repetitive, email
